[2025-03-06T04:57:04.272+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: covid19_etl.create_dim_date scheduled__2025-03-06T04:54:00+00:00 [queued]>
[2025-03-06T04:57:04.317+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: covid19_etl.create_dim_date scheduled__2025-03-06T04:54:00+00:00 [queued]>
[2025-03-06T04:57:04.318+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2025-03-06T04:57:04.319+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2025-03-06T04:57:04.320+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2025-03-06T04:57:04.387+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_dim_date> on 2025-03-06 04:54:00+00:00
[2025-03-06T04:57:04.428+0000] {standard_task_runner.py:55} INFO - Started process 3330 to run task
[2025-03-06T04:57:04.536+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'covid19_etl', 'create_dim_date', 'scheduled__2025-03-06T04:54:00+00:00', '--job-id', '749', '--raw', '--subdir', 'DAGS_FOLDER/covid19-etl.py', '--cfg-path', '/tmp/tmppl4evaee']
[2025-03-06T04:57:04.562+0000] {standard_task_runner.py:83} INFO - Job 749: Subtask create_dim_date
[2025-03-06T04:57:04.991+0000] {task_command.py:376} INFO - Running <TaskInstance: covid19_etl.create_dim_date scheduled__2025-03-06T04:54:00+00:00 [running]> on host e5021ab2b3c4
[2025-03-06T04:57:05.222+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Sharaf
AIRFLOW_CTX_DAG_ID=covid19_etl
AIRFLOW_CTX_TASK_ID=create_dim_date
AIRFLOW_CTX_EXECUTION_DATE=2025-03-06T04:54:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-03-06T04:54:00+00:00
[2025-03-06T04:57:05.288+0000] {base.py:71} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-03-06T04:57:05.306+0000] {sql.py:315} INFO - Running statement: 
            create table if not exists dim_date
            (
                year       integer,
                month      integer,
                month_name varchar,
                day        integer,
                quarter    integer,
                date_id    integer not null primary key
            );
        , parameters: None
[2025-03-06T04:57:05.314+0000] {postgres.py:96} INFO - NOTICE:  relation "dim_date" already exists, skipping

[2025-03-06T04:57:05.347+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=covid19_etl, task_id=create_dim_date, execution_date=20250306T045400, start_date=20250306T045704, end_date=20250306T045705
[2025-03-06T04:57:05.392+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2025-03-06T04:57:05.482+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
